name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main # Replace with the name of the branch you want to sync
          token: ${{ secrets.SYNC }}

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add upstream remote
        run: git remote add upstream  https://github.com/gpakosz/.tmux # Replace with the URL of the original repository

      - name: Fetch changes from upstream
        run: git fetch upstream

      - name: Merge changes from upstream
        run: git merge upstream/main # Replace with the name of the branch you want to merge

      - name: Push changes to fork
        run: git push origin main # Replace with the name of the branch you want to sync
